language: rust

rust:
  - nightly

install:
  - rustup target add --toolchain=nightly wasm32-unknown-unknown
  - cargo +nightly install --git https://github.com/rustwasm/wasm-bindgen/ wasm-bindgen-cli

script:
  - make test
  - make release

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  on:
    branch: master
