language: rust

rust:
  - nightly

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add --toolchain=nightly wasm32-unknown-unknown

script:
  - make test
  - make release

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  on:
    branch: master
